-- SPDX-FileCopyrightText: 2026 Felipe Balbi
-- SPDX-License-Identifier: CERN-OHL-P-2.0
{-# LANGUAGE NumericUnderscores #-}

{- |
16x-oversample enable for the UART: a 1-cycle pulse at (16 * baud) average,
generated by an NCO phase accumulator in the system domain. f_clk is taken from
the domain period, so the 100/32 = 3.125 fractional ratio needs no PLL.
-}
module Tamal.Uart.BaudGen
  ( oversampleTick
  ) where

import Clash.Prelude

oversampleTick ::
  forall baud dom.
  (HiddenClockResetEnable dom, KnownDomain dom, KnownNat baud) =>
  SNat baud ->
  Signal dom Bool
oversampleTick baud = tick
 where
  periodPs :: Integer
  periodPs = snatToNum (SNat @(DomainPeriod dom))
  fClk :: Unsigned 32
  fClk = fromInteger (1_000_000_000_000 `div` periodPs)
  inc :: Unsigned 32
  inc = fromInteger (16 * snatToNum baud)
  sums :: Signal dom (Unsigned 32)
  sums = (+ inc) <$> acc
  tick :: Signal dom Bool
  tick = (>= fClk) <$> sums
  acc :: Signal dom (Unsigned 32)
  acc = register 0 acc'
  acc' :: Signal dom (Unsigned 32)
  acc' = mux tick (subtract fClk <$> sums) sums
