-- SPDX-FileCopyrightText: 2026 Felipe Balbi
-- SPDX-License-Identifier: CERN-OHL-P-2.0
{-# LANGUAGE NumericUnderscores #-}

{- |
16x-oversample enable for the UART: a 1-cycle pulse at (16 * baud) average,
generated by an NCO phase accumulator in the system domain. f_clk is taken from
the domain period, so the 100/32 = 3.125 fractional ratio needs no PLL.
-}
module Tamal.Uart.BaudGen
  ( oversampleTick
  ) where

import Clash.Prelude

{- | The 16x oversample enable, generated by a numerically-controlled oscillator
(NCO). Each cycle the phase accumulator gains @inc = 16*baud@; when it reaches
the modulus @fClk@ it wraps and emits a one-cycle @True@. That yields exactly 16
ticks per bit at 2 Mbaud, at 32 MHz average — with no PLL and no second clock
domain, which matters because @100/32 = 3.125@ is not an integer.
-}
oversampleTick ::
  forall baud dom.
  (HiddenClockResetEnable dom, KnownDomain dom, KnownNat baud) =>
  SNat baud ->
  Signal dom Bool
oversampleTick baud = tick
 where
  -- Clock period in picoseconds, read from the domain type at compile time.
  periodPs :: Integer
  periodPs = snatToNum (SNat @(DomainPeriod dom))
  -- Modulus: the system clock in Hz (100e6 for Dom100).
  fClk :: Unsigned 32
  fClk = fromInteger (1_000_000_000_000 `div` periodPs)
  -- Phase increment per cycle: the target oversample rate, 16 * baud.
  inc :: Unsigned 32
  inc = fromInteger (16 * snatToNum baud)
  -- Candidate next accumulator value (this cycle's acc plus the increment).
  sums :: Signal dom (Unsigned 32)
  sums = (+ inc) <$> acc
  -- Tick whenever the accumulator reaches/exceeds the modulus (the output).
  tick :: Signal dom Bool
  tick = (>= fClk) <$> sums
  -- The accumulator register, fed back through 'register' (the flip-flop).
  acc :: Signal dom (Unsigned 32)
  acc = register 0 acc'
  -- Next accumulator: wrap by subtracting the modulus on a tick, else keep it.
  acc' :: Signal dom (Unsigned 32)
  acc' = mux tick (subtract fClk <$> sums) sums
